### ISSUE TITLE
Nvidia 104-100 Support (Cuda 8.))

### ISSUE THREAD

**Issue by rolandch** [zcoinofficial/ccminer#8]
Any plans to support Nvidia P104-100 (basically a GTX1060 without video output)? Needs Cuda 8.0.

If not, how can I compile it for win64 using Cuda 8.0?

**Comment by djm34** [comment]
I can make a release with cuda 8, no problem. 
Otherwise compilation with cuda 8 is as straight forward as for the other, you just need to go in "build properties" and check cuda 8 instead of cuda 10. you will probably also have to change the cuda compute/sm version. Which is 6.1 (actually it could be the reason why you can't get it to run, probably worth a try to add or replace compute_61, sm_61 by compute_52,sm_52 (or 50)

**Comment by rolandch** [comment]
Thanks.
